[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/netlify/functions"

[functions]
  node_bundler = "esbuild"

# This schedules your ingest to run every 10 minutes
[functions."ingest"]
  schedule = "*/10 * * * *"

[[plugins]]
  package = "@netlify/plugin-functions-core"
