[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/netlify/functions"

[functions]
  node_bundler = "esbuild"

# Scheduled functions are now a native feature, no plugin required!
[functions."ingest"]
  schedule = "*/10 * * * *"